# Generated by Django 4.1.1 on 2022-09-24 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_departamento_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipousuario',
            name='estado',
            field=models.IntegerField(default=1, max_length=11),
        ),
    ]
