# Generated by Django 4.1.1 on 2022-09-24 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_categoria'),
        ('api', '0004_tipousuario_estado'),
    ]

    operations = [
    ]
