# Generated by Django 4.1.1 on 2022-09-28 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='platillos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('precio', models.FloatField(max_length=200)),
                ('stock', models.IntegerField(max_length=11)),
                ('estado', models.IntegerField(default=1, max_length=11)),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.categoria')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.usuario')),
            ],
        ),
    ]
