# Generated by Django 4.1.1 on 2022-09-28 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_platillos'),
    ]

    operations = [
        migrations.CreateModel(
            name='pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('cantidad', models.IntegerField(default=1, max_length=11)),
                ('total', models.FloatField(max_length=200)),
                ('ubicacion', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado_pedido', models.CharField(choices=[('p', 'Proceso'), ('E', 'Enviado'), ('ET', 'Entregado')], default='p', max_length=2)),
                ('estado', models.IntegerField(default=1, max_length=11)),
                ('id_platillo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.platillos')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.usuario')),
            ],
        ),
    ]
