# Generated by Django 4.1.1 on 2022-10-04 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_pedidos'),
    ]

    operations = [
        migrations.AddField(
            model_name='platillos',
            name='oferta',
            field=models.IntegerField(default=0, max_length=11),
        ),
    ]
