# Generated by Django 4.1.1 on 2022-10-05 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_platillos_oferta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='usuario',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
