# Generated by Django 4.1.1 on 2022-10-20 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_platillos_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='platillos',
            name='precio_oferta',
            field=models.FloatField(default=0, max_length=200),
        ),
    ]
